backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "content"
    label: "Contenido"
    files:
      - label: "Eventos"
        name: "events"
        file: "content/events.json"
        format: "json"
        fields:
          - label: "Eventos"
            name: "events"
            widget: "list"
            fields:
              - { label: "Fecha", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false }
              - { label: "Título (ES)", name: "title_es", widget: "string" }
              - { label: "Título (EN)", name: "title_en", widget: "string" }
              - { label: "Lugar (ES)", name: "where_es", widget: "string", required: false }
              - { label: "Lugar (EN)", name: "where_en", widget: "string", required: false }
