backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "events"
    label: "Eventos"
    folder: "content/events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Title (Spanish)", name: "title_es", widget: "string" }
      - { label: "Title (English)", name: "title_en", widget: "string" }
      - { label: "Location Spanish", name: "where_es", widget: "string" }
      - { label: "Location English", name: "where_en", widget: "string" }
